### ISSUE TITLE
Release 0.9.0

### ISSUE THREAD

**Issue by rflbianco** [envygeeks/docker-template#23]
Hi! We have started using docker-template to manage various of our base images. It has been quite annoying to use bundler to install it (pointing to master). Specially because we need to instruct users not versed on Ruby. It would be great to have 0.9.0 released with the current code (master) on rubygems, so we would rather use 'gem install docker-template' system-wide.

Thanks! And congrats for your work.

**Comment by envygeeks** [comment]
Even though it's pre 1.0.0 so people should expect major breakages between releases, I neglected to do so because there were so many breaking changes between master and the last release that was made and I don't rememeber if I ever completed all of my backlog.  I'll take a look sometime this week and see what I can do.

**Comment by rflbianco** [comment]
Firstly, thanks for your quick reply. I understand your point and will wait for a position when possible. I just want to add some things.

Even though it breaks a lot from previous version, as you pointed out, it is pre-1.0. Accordingly to Semver is just right to break completely from 0.8.0, and your clients are well informed about it.

Moreover, we haven't used other images than "normal" so far. It has worked pretty good for us in various scenarios. Obviously, it is needed to check about the other types. But, I feel confident about things are quite OK for a release, considering pre-1.0.

Finally, I also offer me to help if there's something you think I may be helpful. Maybe finishing some implementation or testing. I'm not a Ruby developer, but I believe I can manage to play around, as I have done.

Cheers.

**Comment by envygeeks** [comment]
I was around long before "semver" and using the "scheme" they "created" long before they "thought of it", I've never read it (though admittedly I've invoked it a few times on another project.) So whatever it has to say on the subject matters little to me (not to be offensive.) :wink:

Releases are based on major services that use this software and yes we find it acceptable pre-1.0 to break stuff but only if we fix our stuff that is using it before we break it, there are thousands of images that rely on this software to build automated images.

You'll probably see a release in a few days.

**Comment by envygeeks** [comment]
This has since been fixed, we've released two times.
